# Generated by Django 4.0.1 on 2022-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='symbol',
            new_name='market',
        ),
        migrations.AddField(
            model_name='market',
            name='pprec',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='market',
            name='ib_exchange',
            field=models.CharField(choices=[('CASH', 'CASH'), ('STOCK', 'STOCK'), ('ARCA', 'ARCA'), ('SMART', 'SMART'), ('CME', 'CME'), ('NYM', 'NYM'), ('NYBOT', 'NYBOT'), ('NYB', 'NYB')], default='STOCK', max_length=6),
        ),
        migrations.AlterField(
            model_name='market',
            name='yahoo_exchange',
            field=models.CharField(choices=[('CASH', 'CASH'), ('STOCK', 'STOCK'), ('ARCA', 'ARCA'), ('SMART', 'SMART'), ('CME', 'CME'), ('NYM', 'NYM'), ('NYBOT', 'NYBOT'), ('NYB', 'NYB')], default='STOCK', max_length=6),
        ),
    ]
