# Generated by Django 3.2.8 on 2022-03-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_dailybar_unique_daily_bar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailybar',
            name='unique_daily_bar',
        ),
        migrations.AlterUniqueTogether(
            name='dailybar',
            unique_together={('ticker', 'd')},
        ),
    ]
