# Generated by Django 3.2.8 on 2022-03-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0007_auto_20220301_0911"),
    ]

    operations = [
        migrations.CreateModel(
            name="TBGDailyBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("d", models.DateField()),
                ("o", models.FloatField()),
                ("h", models.FloatField()),
                ("l", models.FloatField()),
                ("c", models.FloatField()),
                ("v", models.FloatField()),
                ("oi", models.FloatField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="markets.ticker"
                    ),
                ),
            ],
            options={
                "unique_together": {("ticker", "d")},
            },
        ),
    ]
