# Generated by Django 4.1.3 on 2024-01-07 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0014_auto_20220817_1705"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticker",
            options={"ordering": ("ticker",)},
        ),
    ]
