# Generated by Django on 2025-12-08

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0015_alter_ticker_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="t_close",
            field=models.TimeField(
                default=datetime.time(16, 0), help_text="Market close time (EST)"
            ),
        ),
    ]
