# Generated by Django 4.0.1 on 2022-02-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0002_rename_symbol_ticker_market_market_pprec_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('reinvest', models.BooleanField(default=True)),
                ('q', models.FloatField()),
                ('p', models.FloatField()),
                ('commission', models.FloatField(blank=True)),
                ('note', models.CharField(blank=True, max_length=180, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.ticker')),
            ],
        ),
    ]
