# Generated by Django 3.2.8 on 2022-02-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField()),
                ("reinvest", models.BooleanField(default=True)),
                ("q", models.FloatField()),
                ("p", models.FloatField()),
                ("commission", models.FloatField(default=0.0)),
                ("note", models.CharField(blank=True, max_length=180, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="markets.ticker"
                    ),
                ),
            ],
        ),
    ]
