# Generated by Django 3.2.8 on 2022-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="trade_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
