# Generated by Django 3.2.8 on 2022-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='reinvest',
            field=models.BooleanField(default=False),
        ),
    ]
