# Generated by Django 4.1.3 on 2023-03-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_trade_q'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['dt']},
        ),
    ]
