# Generated by Django 4.1.3 on 2023-01-10 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_ppmresult_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppmresult',
            name='dt',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
