# Generated by Django 4.1.3 on 2023-01-10 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_alter_ppmresult_dt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ppmresult",
            old_name="dt",
            new_name="d",
        ),
    ]
