# Generated by Django 3.2.8 on 2022-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_cashrecord_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="active_f",
            field=models.BooleanField(default=True),
        ),
    ]
