# Generated by Django 3.2.8 on 2022-09-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_active_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
