# Generated by Django 3.2.8 on 2022-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_account_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="reconciled_f",
            field=models.BooleanField(default=False),
        ),
    ]
