# Generated by Django 4.1.3 on 2023-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_qualified_f"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receivables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoiced", models.DateField(auto_now_add=True)),
                ("expected", models.DateField()),
                ("received", models.DateField()),
                ("description", models.CharField(max_length=180)),
                ("amt", models.FloatField()),
            ],
        ),
    ]
