# Generated by Django 4.1.3 on 2023-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_receivables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receivables',
            new_name='Receivable',
        ),
    ]
