# Generated by Django 4.1.3 on 2023-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_receivables_receivable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivable',
            name='description',
        ),
        migrations.AddField(
            model_name='receivable',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receivable',
            name='invoice',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='expected',
            field=models.DateField(blank=True),
        ),
    ]
