# Generated by Django 4.1.3 on 2023-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_receivable_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivable",
            name="expected",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="received",
            field=models.DateField(blank=True, null=True),
        ),
    ]
