# Generated by Django 4.1.3 on 2023-03-06 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_receivable_expected_alter_receivable_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='invoiced',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
