# Generated by Django 4.1.3 on 2024-01-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_vendor_alter_account_options_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cashrecord'),
        ),
    ]
