# Generated by Django 4.1.3 on 2024-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_expense_cash_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="paid",
            field=models.DateField(
                blank=True,
                help_text="May be different from cash transaction if paid by credit card.",
                null=True,
            ),
        ),
    ]
