# Generated by Django 4.1.3 on 2024-01-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_expense_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cash_transaction',
            field=models.ForeignKey(blank=True, help_text='Cash record where either paid from directly or reimbursed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cashrecord'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid',
            field=models.DateField(blank=True, help_text='May have date different from cash transaction.', null=True),
        ),
    ]
