# Generated by Django 4.1.3 on 2024-02-05 14:50

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_alter_expense_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCashRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('d', models.DateField()),
                ('category', models.CharField(choices=[('AB', 'Avi Bar Mitzvah'), ('AV', 'Deposit to Avi account'), ('BF', 'Bank fee'), ('BNK', 'Bank Check'), ('BM', 'Bar Mitzvah'), ('BH', 'Baltimore House'), ('CH', 'Charity'), ('CE', 'College Expenses'), ('DE', 'Deposits'), ('ED', 'Education/Lessons/Tutoring'), ('FC', 'Food & Clothing'), ('GN', 'General'), ('HO', 'House - Mortgage/Rent/Maintenance/Renovation'), ('HS', 'Health Savings Account'), ('IN', 'Insurance'), ('MD', 'Medical'), ('OL', 'business officers loan to Brookhaven'), ('PR', 'Professional'), ('SA', 'Savings'), ('SB', 'Sailboat'), ('TA', 'Taxes and Accounting'), ('UT', 'Utilities'), ('VA', 'Vacation'), ('WA', 'Wages from tutoring'), ('GB', 'Gila Bat Mitzvah'), ('IT', 'Interest'), ('GU', 'Gila UTMA')], default='GN', max_length=3)),
                ('description', models.CharField(max_length=180)),
                ('amt', models.FloatField()),
                ('cleared_f', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, default=accounts.models.get_bofa_account, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cash record',
                'verbose_name_plural': 'historical cash records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
