# Generated by Django 4.1.3 on 2024-02-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_historicalcashrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCashRecord',
        ),
    ]
