# Generated by Django 5.2.10 on 2026-03-27 18:33

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_tradesize"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivable",
            name="account",
            field=models.ForeignKey(
                default=accounts.models.get_tbg_account_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
    ]
